language: node_js
node_js:
  - 10
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - npm ci
script:
  - npm run ci
if: tag IS present
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key:
    secure: $NPM_DEPLOY_TOKEN
  on:
    branch: master
    tags: true
    repo: davellanedam/vue-skeleton-mvp
